### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by Ace71425** [MohamadZeina/Disco_Diffusion_Local#44]
I'm getting the below error on the final Diffusion step...I have a 3080 12gb and don't think this should be an issue....is there something that is installed incorrectly? Or a default setting that is way too high? I've resolved all errors on the previous steps and everything runs through good and I've tried messing with a few setting to no avail, Thanks!

RuntimeError: CUDA out of memory. Tried to allocate 52.00 MiB (GPU 0; 11.76 GiB total capacity; 9.57 GiB already allocated; 47.50 MiB free; 9.95 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by Ace71425** [comment]
I fixed it....just needed to scale back how many models I was using and tweak the settings a bit...great work on this, it's amazing!
